version: '3.9'
services:
  frontend:
    image: "zenoli/rb-scores-frontend"
    build: "./frontend"
    container_name: "frontend"
    ports:
      - "8080:80"
    environment:
      - API_PROXY=http://backend:3000/
  backend:
    image: "zenoli/rb-scores-backend"
    build: "./backend"
    container_name: "backend"
    ports:
      - "3000:3000"
    env_file:
      - backend/.env
